window.APP_CONFIG = Object.freeze({
  SUPABASE_URL: "https://YOUR_PROJECT_ID.supabase.co",
  SUPABASE_ANON_KEY: "YOUR_SUPABASE_ANON_KEY",
  SUPABASE_GALLERY_BUCKET: "gallery",
  WHATSAPP_NUMBER: "972501234567"
});
